//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RentifyxAssetRegistry.Domain.MessageResource {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ValidationMessageResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ValidationMessageResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RentifyxAssetRegistry.Domain.MessageResource.ValidationMessageResource", typeof(ValidationMessageResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description must not exceed {MaxLength} characters..
        /// </summary>
        public static string DESCRIPTION_MAX_LENGTH {
            get {
                return ResourceManager.GetString("DESCRIPTION_MAX_LENGTH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description is required..
        /// </summary>
        public static string DESCRIPTION_REQUIRED {
            get {
                return ResourceManager.GetString("DESCRIPTION_REQUIRED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name must not exceed {MaxLength} characters..
        /// </summary>
        public static string NAME_MAX_LENGTH {
            get {
                return ResourceManager.GetString("NAME_MAX_LENGTH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name is required..
        /// </summary>
        public static string NAME_REQUIRED {
            get {
                return ResourceManager.GetString("NAME_REQUIRED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Example not found..
        /// </summary>
        public static string EXAMPLE_NOT_FOUND {
            get {
                return ResourceManager.GetString("EXAMPLE_NOT_FOUND", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Page must be greater than or equal to {MinPage}..
        /// </summary>
        public static string PAGE_INVALID {
            get {
                return ResourceManager.GetString("PAGE_INVALID", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to PageSize must be between {MinPageSize} and {MaxPageSize}..
        /// </summary>
        public static string PAGE_SIZE_INVALID {
            get {
                return ResourceManager.GetString("PAGE_SIZE_INVALID", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Title is required..
        /// </summary>
        public static string TITLE_REQUIRED {
            get {
                return ResourceManager.GetString("TITLE_REQUIRED", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Title must be at least {MinLength} characters..
        /// </summary>
        public static string TITLE_MIN_LENGTH {
            get {
                return ResourceManager.GetString("TITLE_MIN_LENGTH", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Title must not exceed {MaxLength} characters..
        /// </summary>
        public static string TITLE_MAX_LENGTH {
            get {
                return ResourceManager.GetString("TITLE_MAX_LENGTH", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Description must be at least {MinLength} characters..
        /// </summary>
        public static string DESCRIPTION_MIN_LENGTH {
            get {
                return ResourceManager.GetString("DESCRIPTION_MIN_LENGTH", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to OwnerId is required..
        /// </summary>
        public static string OWNER_ID_REQUIRED {
            get {
                return ResourceManager.GetString("OWNER_ID_REQUIRED", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to CategoryId is required..
        /// </summary>
        public static string CATEGORY_ID_REQUIRED {
            get {
                return ResourceManager.GetString("CATEGORY_ID_REQUIRED", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to IdempotencyKey is required..
        /// </summary>
        public static string IDEMPOTENCY_KEY_REQUIRED {
            get {
                return ResourceManager.GetString("IDEMPOTENCY_KEY_REQUIRED", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to AssetId is required..
        /// </summary>
        public static string ASSET_ID_REQUIRED {
            get {
                return ResourceManager.GetString("ASSET_ID_REQUIRED", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to MimeType is not an allowed media type..
        /// </summary>
        public static string MIME_TYPE_INVALID {
            get {
                return ResourceManager.GetString("MIME_TYPE_INVALID", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to SizeBytes must be greater than zero..
        /// </summary>
        public static string SIZE_BYTES_INVALID {
            get {
                return ResourceManager.GetString("SIZE_BYTES_INVALID", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to S3Key is required..
        /// </summary>
        public static string S3_KEY_REQUIRED {
            get {
                return ResourceManager.GetString("S3_KEY_REQUIRED", resourceCulture);
            }
        }
    }
}
